application: evdb
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /styles.css
  static_files: styles.css
  upload: styles.css

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
